refactor(upload-operator): add generic to upload operator, return htt…
nilsmehlhorn/ngx-operators pull request #23
Opened 2022-12-30 18:00 UTC by OleksiiSmerdov

…p response body

2022-12-31 14:53 UTC, nilsmehlhorn requested changes
Thanks for the contribution, I've just got two minor comments.

2022-12-31 14:53 UTC, nilsmehlhorn commented on projects/ngx-operators/src/lib/upload.ts
> +        body: (event as HttpResponse<T>).body,
Wondering if this type assertion is necessary as `isHttpResponse`  looks like it narrows to `HttpResponse<T>` already. :thinking:

2022-12-31 14:53 UTC, nilsmehlhorn commented on projects/ngx-operators/src/lib/upload.ts
> +export function upload<T>(): (
How about we default the generic parameter to `unknown`? That way this wouldn't be a breaking change for users of the library

```suggestion
export function upload<T = unknown>(): (
```

2023-01-01 10:15 UTC, OleksiiSmerdov commented on projects/ngx-operators/src/lib/upload.ts
> +        body: (event as HttpResponse<T>).body,
Nope, it's not necessary. Fixed

2023-01-01 10:18 UTC, OleksiiSmerdov commented on projects/ngx-operators/src/lib/upload.ts
> +export function upload<T>(): (
This makes sense. Fixed

2023-01-03 07:33 UTC, nilsmehlhorn approved these changes

2023-01-03 07:33 UTC, merged